name: Publish Book

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - name: Install TinyTeX directly
        run: |
          # Install TinyTeX using the direct installer rather than quarto's command
          wget -qO- "https://yihui.org/tinytex/install-bin-unix.sh" | sh
          # Add TinyTeX to PATH
          echo "$HOME/.TinyTeX/bin/x86_64-linux" >> $GITHUB_PATH
          # Test LaTeX installation
          tlmgr --version
          
      - name: Ensure images directory exists
        run: |
          mkdir -p images
          
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}