name: Publish Book

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      
      - name: Install TinyTeX
        run: |
          # Install required packages first
          sudo apt-get update
          sudo apt-get install -y wget perl
          
          # Create directory and install TinyTeX
          mkdir -p ~/.local/share/tinytex/bin
          wget -qO- "https://yihui.org/tinytex/install-unx.sh" | sh
          
          # Add TinyTeX to PATH
          echo "$HOME/.local/share/tinytex/bin" >> $GITHUB_PATH
          
          # Wait for PATH to update
          sleep 5
          
          # Verify installation
          which pdflatex || echo "pdflatex not found"
          ls -la ~/.local/share/tinytex/bin || echo "TinyTeX bin directory not found or empty"
          
      - name: Ensure images directory exists
        run: |
          mkdir -p images
          
      - name: Simple placeholder cover
        run: |
          sudo apt-get install -y imagemagick
          convert -size 800x1200 xc:blue -gravity center \
            -pointsize 48 -fill white -annotate 0 "From Zero to Production" \
            -pointsize 28 -fill white -annotate +0+80 "A Practical Python Development Pipeline" \
            -pointsize 24 -fill white -annotate +0+150 "Michael Borck" \
            images/cover.png
          
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}